"""Remove typo column

Revision ID: 4284fbd361a4
Revises: d6c82d09f039
Create Date: 2023-08-13 18:50:39.569794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4284fbd361a4'
down_revision: Union[str, None] = 'd6c82d09f039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_something', table_name='tasks')
    op.drop_column('tasks', 'something')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('something', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_tasks_something', 'tasks', ['something'], unique=False)
    # ### end Alembic commands ###
