"""Add project_id

Revision ID: b384d115720b
Revises: e174d04bb825
Create Date: 2023-08-14 15:56:17.041307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b384d115720b'
down_revision: Union[str, None] = 'e174d04bb825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_name_key', 'projects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('projects_name_key', 'projects', ['name'])
    # ### end Alembic commands ###
