projects_service:
  replicaCount: 1
  image:
    repository: localhost:5000/projects_service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8002
  env:
    - name: PROJECTS_SERVICE_URL
      value: "http://projects-service:8002/projects"