"""Update models structure

Revision ID: 4e56c1e3db1c
Revises: 7a6ec25d69e7
Create Date: 2023-08-20 17:58:40.514179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e56c1e3db1c'
down_revision: Union[str, None] = '7a6ec25d69e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
