"""Update models structure

Revision ID: 5cefc755b5aa
Revises: 555067bba0b7
Create Date: 2023-08-20 17:40:18.305296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cefc755b5aa'
down_revision: Union[str, None] = '555067bba0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subtasks_description', table_name='subtasks')
    op.drop_index('ix_subtasks_id', table_name='subtasks')
    op.drop_index('ix_subtasks_title', table_name='subtasks')
    op.drop_table('subtasks')
    op.add_column('tasks', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_id')
    op.create_table('subtasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], name='subtasks_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subtasks_pkey')
    )
    op.create_index('ix_subtasks_title', 'subtasks', ['title'], unique=False)
    op.create_index('ix_subtasks_id', 'subtasks', ['id'], unique=False)
    op.create_index('ix_subtasks_description', 'subtasks', ['description'], unique=False)
    # ### end Alembic commands ###
