users_service:
  replicaCount: 1
  image:
    repository: localhost:5000/users_service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8004
  env:
    - name: USERS_SERVICE_URL
      value: "http://users-service:8004/users"